version: '3'
services:
  pyspark_app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
      - ./scripts:/app/scripts
    depends_on:
      - postgres_db
    networks:
      - my_network
    environment:
      - POSTGRES_HOST=postgres_db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=......
      - POSTGRES_DB=travelbooking

  postgres_db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123qwE!@#
      - POSTGRES_DB=travelbooking
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    networks:
      - my_network

networks:
  my_network:
    name: diskbird_network